version: "3.7"
services:
    gambler_overflow:
        container_name: gambler_overflow
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        ports:
            - "9203:1337"
